import type {
  Quotation,
  QuotationCharge,
  QuotationItem,
  QuotationListItem,
  QuotationTax,
} from '../../types'

/** Shared quotation fixtures. One shape, so a contract change fails every test at once. */

export const quotationListItem = (over: Partial<QuotationListItem> = {}): QuotationListItem => ({
  id: 'q1',
  quotationNumber: 'QT-2026-000001',
  revisionNumber: 1,
  type: 'FIRM',
  buyerId: 'acc1',
  primaryRfqId: null,
  title: 'Q3 spice programme',
  currency: 'USD',
  baseCurrency: 'USD',
  fxRate: null,
  incoterm: 'CIF',
  destinationCountry: 'AE',
  destinationPort: 'Jebel Ali',
  paymentTermId: null,
  validFrom: null,
  validUntil: null,
  status: 'DRAFT',
  subtotal: '1000',
  chargesTotal: '150',
  discountTotal: '50',
  taxTotal: '55',
  grandTotal: '1155',
  previousRevisionId: null,
  supersededAt: null,
  sentAt: null,
  acceptedAt: null,
  version: 1,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  deletedAt: null,
  ...over,
})

export const quotationItem = (over: Partial<QuotationItem> = {}): QuotationItem => ({
  id: 'i1',
  lineNumber: 1,
  productId: null,
  customProductName: 'Turmeric powder',
  description: null,
  rfqItemId: null,
  quantity: '10',
  unit: 'MT',
  unitCost: '80',
  marginPercent: '20',
  unitPrice: '100',
  lineSubtotal: '1000',
  lineTotal: '1000',
  packaging: null,
  hsCode: null,
  countryOfOrigin: null,
  requiredCertifications: [],
  leadTimeDays: null,
  version: 1,
  product: null,
  ...over,
})

export const charge = (over: Partial<QuotationCharge> = {}): QuotationCharge => ({
  id: 'c1',
  quotationItemId: null,
  type: 'FREIGHT',
  scope: 'HEADER',
  basis: 'FIXED_AMOUNT',
  label: 'Ocean freight',
  rate: null,
  amount: '150',
  currency: 'USD',
  isDeduction: false,
  sequence: 0,
  isVisibleToCustomer: true,
  version: 1,
  ...over,
})

export const tax = (over: Partial<QuotationTax> = {}): QuotationTax => ({
  id: 't1',
  quotationItemId: null,
  type: 'GST',
  code: null,
  jurisdiction: 'India',
  ratePercent: '5',
  taxableAmount: '1100',
  amount: '55',
  currency: 'USD',
  isCompound: false,
  isReverseCharge: false,
  sequence: 0,
  version: 1,
  ...over,
})

export const quotation = (over: Partial<Quotation> = {}): Quotation => ({
  ...quotationListItem(),
  description: null,
  namedPlace: null,
  paymentTermsText: null,
  leadTimeDays: null,
  packingSummary: null,
  samplingTerms: null,
  costTotal: '800',
  marginPercent: '20',
  rejectedAt: null,
  rejectionReason: null,
  createdById: 'u1',
  items: [quotationItem()],
  charges: [charge()],
  taxes: [tax()],
  ...over,
})

/** The same quotation as seen by a role that cannot `manage Account`. */
export const redacted = (over: Partial<Quotation> = {}): Quotation =>
  quotation({
    costTotal: null,
    marginPercent: null,
    items: [quotationItem({ unitCost: null, marginPercent: null })],
    ...over,
  })
